#version 450

struct Material{
    ivec4 texturesIds; // x = albedo, y = normal, z = roughness, w = metallic
    vec4 albedo;
    vec4 ambient;
    vec4 emission;
    float roughness;
    float metallic;
    vec2 _pad;
};

struct Mesh {
    Material material;
    uint transformId;   
    uint pipelineId;       
    uint meshInfoId;
    uint valid;
};

// Struktur für eine einzelne Instanz im Eingabepuffer
struct MeshInstance {
    Mesh mesh;
    uint id;
    // Match C++ MeshInstance: Mesh (96) + id and padding (16).
    uint pad0;
    uint pad1;
    uint pad2;
};

// Layout-Konfiguration für die Ausführung (Workgroup-Größe)
layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

// Eingabepuffer: Enthält die Instanz-Daten
layout(std430, binding = 0) readonly buffer InputBuffer {
    MeshInstance instances[];
};

// Ausgabepuffer: Hier werden die Meshes an die Position ihrer ID geschrieben
layout(std430, binding = 1) writeonly buffer MeshBuffer {
    Mesh meshes[];
};

layout(push_constant) uniform PushConstants {
    uint instanceBufferSize;
} pc;


void main() {
    uint index = gl_GlobalInvocationID.x;

    if (index >= pc.instanceBufferSize) {
        return;
    }

    MeshInstance instance = instances[index];
    meshes[instance.id] = instance.mesh;
}
